### ISSUE TITLE
How to use group alias to map account numbers to account aliases

### ISSUE THREAD

**Issue by thetombombadil** [electrolux-oss/aws-cost-exporter#26]
Hi! Thanks you for the great tool.

I'm trying to wrap my head around the new group aliases feature added recently [here](https://github.com/electrolux-oss/aws-cost-exporter/pull/24). My understanding of the new group aliases feature is it can be used to export additional prometheus labels derived from mapping values. With that in mind **I'd like to use the new group alias feature to map human-readable account names to the account numbers that are currently exported as prometheus labels.** Please let me know if I misunderstood this feature.

We have a root account that is linked to all our billable accounts - this is where I've set up aws-cost-exporter to fetch costs from which works as expected, and I can see all the costs there from all the linked accounts. 

Image used: `opensourceelectrolux/aws-cost-exporter:v1.0.10`

Snippet example of metrics/target_aws_accounts that I'm using (with account numbers redacted):

```yaml
metrics:
  - metric_name: aws_daily_cost_by_service_by_account
    group_by:
      enabled: true
      groups:
        - type: DIMENSION
          key: SERVICE
          label_name: ServiceName
        - type: DIMENSION
          key: LINKED_ACCOUNT
          label_name: AccountName
          alias:
            label_name: AccountAlias
            map:
              "123456789012": "root" # the root account where the exporter fetches costs from - also a publisher
              "234567890123": "staging" # staging account, linked costs from root account
              "321645789123": "production" # production account, linked costs from root account
      merge_minor_cost:
        # if this is enabled, minor cost that is below the threshold will be merged into one group
        enabled: true
        threshold: 10
        tag_value: Other
    # Allowed values for metric type are AmortizedCost, BlendedCost, NetAmortizedCost, NetUnblendedCost, NormalizedUsageAmount, UnblendedCost, and UsageQuantity
    metric_type: AmortizedCost

target_aws_accounts:
  - Publisher: 123456789012
 
```

With this snippet used in the config, it looks like these labels are exported by cost explorer for the `aws_daily_cost_by_service_by_account` metric:
- `AccountName`
- `ChargeType`
- `Publisher`
- `ServiceName`

However I am also expecting the label `AccountAlias` to be exported in addition to the other labels, which it is not currently. If this is not the intention, I may look at prometheus relabelling as the alternative, however I wanted to implement this first.

I also get the error `Incorrect label names` if I have specific accounts in the alias map - however I'm struggling to narrow down the exact symptoms for this.

Thank you in advance!

**Comment by gluckzhang** [comment]
Hi again, indeed, I have reproduced the error and found the root cause. It has been fixed by this #29. I will release a new version soon, maybe by the end of this week. Cheers!

**Comment by sysadmin-exe** [comment]
Hi @gluckzhang 
Thanks for working on this. I am using the latest version of the docker image which has this change applied but I still see this issue. Aliases do not work for all the accounts listed.

**Comment by gluckzhang** [comment]
> Hi [@gluckzhang](https://github.com/gluckzhang?rgh-link-date=2025-03-31T19%3A26%3A35.000Z) Thanks for working on this. I am using the latest version of the docker image which has this change applied but I still see this issue. Aliases do not work for all the accounts listed.

Hi @sysadmin-exe, thanks for reaching out. I was OOO last week and just read the message. Will check it out when I am free and get back to you later :)

**Comment by gluckzhang** [comment]
Hi @sysadmin-exe, sorry about the late reply. I tested from the `main` branch and used the following configuration:

```yaml
...
metrics:
  - metric_name: aws_daily_cost_by_service_by_account # change the metric name if needed
    group_by:
      enabled: true
      groups:
        - type: DIMENSION
          key: SERVICE
          label_name: ServiceName
        - type: DIMENSION
          key: LINKED_ACCOUNT
          label_name: AccountName
          alias:
            label_name: AccountAlias
            map:
              "<12-dig-aws-account-here>": "sandbox"

target_aws_accounts:
  - Publisher: <12-dig-aws-account-here>
```

I can see each metric contains the label `AccountAlias` with the value `sandbox`. Could you share what config are you using so that I can double-check?

**Comment by sysadmin-exe** [comment]
Thanks @gluckzhang for looking into this and responding. This is my config 
```
  - metric_name: aws_daily_cost_by_service_by_account
    group_by:
      enabled: true
      groups:
        - type: DIMENSION
          key: SERVICE
          label_name: ServiceName
        - type: DIMENSION
          key: LINKED_ACCOUNT
          label_name: AccountName
          alias: 
            label_name: AccountAlias
            map:
              "123456789012": "RootAccount"
              "098765432123": "Dev"
              "123455454444": "staging
              "1222222222222": "QA"
              "3222223333333": "prod"
              "123456789012": "sandbox"
      merge_minor_cost:
        enabled: false
        threshold: 10
        tag_value: other  
    metric_type: UnblendedCost

target_aws_accounts:
  - Publisher: 123456789012

```

In this case, only 3 accounts showed (I think just the first 3 but not sure). The others did not show when I queried based on `AccountAlias`

**Comment by gluckzhang** [comment]
Hi @sysadmin-exe , aha I see, so you mean some of the accounts are missing, right? We recently fixed a bug about the next page token handling https://github.com/electrolux-oss/aws-cost-exporter/commit/d43e513e3ec581aa020f1659596970d1d3e017a4, could you please check if the version you used already contains this fix? Or maybe a quicker way is to test it again with the latest Docker image.

**Comment by sysadmin-exe** [comment]
Oh! Thanks! I will check it out. I just checked again and saw that I did not use the latest version.
